name: Update sign-data.json on new issue

on:
  issues:
    types: [opened]

permissions:
  contents: write 

jobs:
  update-issue-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up jq
        run: sudo apt-get install jq

      - name: Create public directory if not exists
        run: mkdir -p public

      - name: Generate issue.json
        run: |
          jq -n \
            --arg id "${{ github.event.issue.id }}" \
            --arg body "${{ github.event.issue.body }}" \
            --arg created_at "${{ github.event.issue.created_at }}" \
            --arg author "${{ github.event.issue.user.login }}" \
            '{
              id: ($id | tonumber),
              body: $body,
              created_at: $created_at,
              author: $author
            }' > my-page/public/issue.json

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit and push issue.json
        run: |
          git pull --rebase origin main
          git add public/issue.json
          git commit -m "Update issue.json from #${{ github.event.issue.number }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.AUTH_TOKEN }}@github.com/mete0rfish/mete0rfish.github.io.git
