name: Update sign-data.json on new issue

on:
  issues:
    types: [opened]

permissions:
  contents: write 

jobs:
  update-issue-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up jq
        run: sudo apt-get install jq

      - name: Create public directory if not exists
        run: mkdir -p public

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Ensure sign-data.json is a valid JSON array
        run: |
          FILE="my-page/public/sign-data.json"
          if [ ! -f "$FILE" ]; then
            echo "[]" > "$FILE"
          else
            type=$(jq 'type' "$FILE" 2>/dev/null || echo "null")
            if [ "$type" != "\"array\"" ]; then
              echo "[]" > "$FILE"
            fi
          fi

      - name: Pull latest main
        run: |
          git stash --include-untracked
          git pull --rebase origin main
          git stash pop || true

      - name: Generate issue.json
        run: |
          FILE="my-page/public/sign-data.json"

          new_entry=$(jq -n \
            --arg id "${{ github.event.issue.id }}" \
            --arg body "${{ github.event.issue.body }}" \
            --arg created_at "${{ github.event.issue.created_at }}" \
            --arg author "${{ github.event.issue.user.login }}" \
            '{
              id: ($id | tonumber),
              body: $body,
              created_at: $created_at,
              author: $author
            }')

          tmp_file=$(mktemp)
          jq ". += [ $new_entry ]" "$FILE" > "$tmp_file" && mv "$tmp_file" "$FILE"

      - name: Commit and push issue.json
        run: |
          git add my-page/public/sign-data.json
          git commit -m "Update sign-data.json from #${{ github.event.issue.number }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.AUTH_TOKEN }}@github.com/mete0rfish/mete0rfish.github.io.git
